List<Map<String, String>> city = [
  {'key': 'Select', 'value': 'null'},
  {'key': 'ঢাকা-মেট্রো', 'value': 'DHAKA METRO'},
  {'key': 'ফরিদপুর', 'value': 'FARIDPUR'},
  {'key': 'গাজীপুর', 'value': 'GAZIPUR'},
  {'key': 'গোপালগঞ্জ', 'value': 'GOPALGANJ'},
  {'key': 'জামালপুর', 'value': 'JAMALPUR'},
  {'key': 'কিশোরগঞ্জ', 'value': 'KISHOREGANJ'},
  {'key': 'মাদারীপুর', 'value': 'MADARIPUR'},
  {'key': 'মানিকগঞ্জ', 'value': 'MANIKGANJ'},
  {'key': 'মুন্সীগঞ্জ', 'value': 'MUNSHIGANJ'},
  {'key': 'ময়মনসিংহ', 'value': 'MYMENSINGH'},
  {'key': 'নারায়ণগঞ্জ', 'value': 'NARAYANGANJ'},
  {'key': 'নরসিংদী', 'value': 'NARSINGDI'},
  {'key': 'নেত্রকোনা', 'value': 'NETROKONA'},
  {'key': 'রাজবাড়ী', 'value': 'RAJBARI'},
  {'key': 'শরীয়তপুর', 'value': 'SHARIATPUR'},
  {'key': 'শেরপুর', 'value': 'SHERPUR'},
  {'key': 'টাঙ্গাইল', 'value': 'TANGAIL'},
  {'key': 'বগুড়া', 'value': 'BOGRA'},
  {'key': 'জয়পুরহাট', 'value': 'JOYPURHAT'},
  {'key': 'নওগাঁ', 'value': 'NAOGAON'},
  {'key': 'নাটোর', 'value': 'NATORE'},
  {'key': 'নবাবগঞ্জ', 'value': 'NAWABGANJ'},
  {'key': 'পাবনা', 'value': 'PABNA'},
  {'key': 'রাজশাহী', 'value': 'RAJSHAHI'},
  {'key': 'সিরাজগঞ্জ', 'value': 'SIRAJGONJ'},
  {'key': 'দিনাজপুর', 'value': 'DINAJPUR'},
  {'key': 'গাইবান্ধা', 'value': 'GAIBANDHA'},
  {'key': 'কুড়িগ্রাম', 'value': 'KURIGRAM'},
  {'key': 'লালমনিরহাট', 'value': 'LALMONIRHAT'},
  {'key': 'নীলফামারী', 'value': 'NILPHAMARI'},
  {'key': 'পঞ্চগড়', 'value': 'PANCHAGARH'},
  {'key': 'রংপুর', 'value': 'RANGPUR'},
  {'key': 'ঠাকুরগাঁও', 'value': 'THAKURGAON'},
  {'key': 'বরগুনা', 'value': 'BARGUNA'},
  {'key': 'বরিশাল', 'value': 'BARISAL'},
  {'key': 'ভোলা', 'value': 'BHOLA'},
  {'key': 'ঝালকাঠি', 'value': 'JHALOKATI'},
  {'key': 'পটুয়াখালী', 'value': 'PATUAKHALI'},
  {'key': 'পিরোজপুর', 'value': 'PIROJPUR'},
  {'key': 'বান্দরবান', 'value': 'BANDARBAN'},
  {'key': 'ব্রাহ্মণবাড়িয়া', 'value': 'BRAHMANBARIA'},
  {'key': 'চাঁদপুর', 'value': 'CHANDPUR'},
  {'key': 'চট্টগ্রাম', 'value': 'CHITTAGONG'},
  {'key': 'কুমিল্লা', 'value': 'COMILLA'},
  {'key': 'কক্সবাজার', 'value': 'COX' 'S BAZAR'},
  {'key': 'ফেনী', 'value': 'FENI'},
  {'key': 'খাগড়াছড়ি', 'value': 'KHAGRACHARI'},
  {'key': 'লক্ষ্মীপুর', 'value': 'LAKSHMIPUR'},
  {'key': 'নোয়াখালী', 'value': 'NOAKHALI'},
  {'key': 'রাঙ্গামাটি', 'value': 'RANGAMATI'},
  {'key': 'হবিগঞ্জ', 'value': 'HABIGANJ'},
  {'key': 'মৌলভীবাজার', 'value': 'MAULVIBAZAR'},
  {'key': 'সুনামগঞ্জ', 'value': 'SUNAMGANJ'},
  {'key': 'সিলেট', 'value': 'SYLHET'},
  {'key': 'বাগেরহাট', 'value': 'BAGERHAT'},
  {'key': 'চুয়াডাঙ্গা', 'value': 'CHUADANGA'},
  {'key': 'যশোর', 'value': 'JESSORE'},
  {'key': 'ঝিনাইদহ', 'value': 'JHENAIDAH'},
  {'key': 'খুলনা', 'value': 'KHULNA'},
  {'key': 'কুষ্টিয়া', 'value': 'KUSHTIA'},
  {'key': 'মাগুরা', 'value': 'MAGURA'},
  {'key': 'মেহেরপুর', 'value': 'MEHERPUR'},
  {'key': 'নড়াইল', 'value': 'NARAIL'},
  {'key': 'সাতক্ষীরা', 'value': 'SATKHIRA'},
];

List<Map<String, String>> vehicleClassLetter = [
  {'key': 'Select', 'value': 'null'},
  {'key': 'এ', 'value': 'A'},
  {'key': 'হ', 'value': 'HA'},
  {'key': 'ল', 'value': 'LA'},
  {'key': 'ক', 'value': 'KA'},
  {'key': 'খ', 'value': 'KHA'},
  {'key': 'গ', 'value': 'GA'},
  {'key': 'ভ', 'value': 'BHA'},
  {'key': 'ঘ', 'value': 'GHA'},
  {'key': 'চ', 'value': 'CHA'},
  {'key': 'প', 'value': 'PA'},
  {'key': 'ছ', 'value': 'CAA'},
  {'key': 'জ', 'value': 'JA'},
  {'key': 'ঝ', 'value': 'JHA'},
  {'key': 'ব', 'value': 'BA'},
  {'key': 'স', 'value': 'SA'},
  {'key': 'ত', 'value': 'TWA'},
  {'key': 'থ', 'value': 'TAW'},
  {'key': 'দ', 'value': 'DWA'},
  {'key': 'ফ', 'value': 'FA'},
  {'key': 'ঠ', 'value': 'THA'},
  {'key': 'ম', 'value': 'MA'},
  {'key': 'ন', 'value': 'NA'},
  {'key': 'অ', 'value': 'AU'},
  {'key': 'ড', 'value': 'DA'},
  {'key': 'উ', 'value': 'U'},
  {'key': 'ট', 'value': 'TA'},
  {'key': 'ঢ', 'value': 'DHA'},
  {'key': 'শ', 'value': 'SHA'},
  {'key': 'ই', 'value': 'E'},
];

List<String> banglaCityNames = city.map((map) => map['key']!).toList();
List<String> banglaVehicleClassLetter =
    vehicleClassLetter.map((map) => map['key']!).toList();


